# Generated by Django 4.2.8 on 2023-12-27 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_cert', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gradeturma',
            name='fk_in_ex',
        ),
        migrations.AddField(
            model_name='gradeturma',
            name='externo',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Externo'),
        ),
        migrations.AddField(
            model_name='gradeturma',
            name='interno',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Interno'),
        ),
    ]
