# Generated by Django 4.2.5 on 2023-12-05 19:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_cert', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gradeturma',
            name='fk_in_ex',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_cert.in_ex', verbose_name='FK Tipo Interno Externo'),
        ),
        migrations.AlterField(
            model_name='gradeturma',
            name='fk_instrucao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_cert.instrucao', verbose_name='FK Instrução'),
        ),
        migrations.AlterField(
            model_name='gradeturma',
            name='tempo_instrucao',
            field=models.IntegerField(blank=True, null=True, verbose_name='Tempo da Instrução'),
        ),
        migrations.AlterField(
            model_name='turma',
            name='turma',
            field=models.CharField(max_length=50, verbose_name='Descrição no certificado:'),
        ),
    ]
