# Generated by Django 5.0 on 2023-12-14 17:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_cert', '0003_remove_gradeturma_fk_in_ex_gradeturma_externo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gradeturma',
            name='externo',
        ),
        migrations.RemoveField(
            model_name='gradeturma',
            name='interno',
        ),
        migrations.AddField(
            model_name='gradeturma',
            name='fk_in_ex',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_cert.in_ex', verbose_name='FK Tipo Interno Externo'),
        ),
    ]
