# Generated by Django 5.0.2 on 2024-10-03 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_cert', '0003_alter_aluno_fk_forca_orgao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turma',
            name='turma',
            field=models.CharField(max_length=150, verbose_name='Descrição que irá aparecer no certificado:'),
        ),
    ]
