from .views_aluno import *
from .views_ano import *
from .views_certificado import *
from .views_curso import *
from .views_grade import *
from .views_home import *
from .views_imagem import *
from .views_import import *
from .views_instrucao import *
from .views_modelo import *
from .views_pdf import *
from .views_status import *
from .views_textos import *
from .views_tipo import *
from .views_tratamento import *
from .views_turma import *